[package]
name = "schengen"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
thiserror = "2.0"
tokio = { version = "1", features = ["net", "time", "rt", "rt-multi-thread", "io-util", "sync", "macros"] }
log = "0.4"
